export const schemes=[
{id:'sch-wb01',name:'Annapurna Bhandar Scheme',short:'Financial assistance to small grocery/kirana shop owners to strengthen local retail.',category:'Livelihood',state:'West Bengal',authority:'Department of Micro, Small & Medium Enterprises, WB',benefit:'One-time financial assistance for small retailers',age:{min:21,max:60},incomeMax:400000,occupations:['Self-employed','Other'],categories:['SC','ST','OBC','General'],gender:['Any'],disability:'Any',documents:['Aadhaar','Trade License','Bank Account Proof'],applicationUrl:'https://socialsecurity.wb.gov.in/'},
{id:'sch-wb02',name:'Yuvashree Prakalpa (Yuva Sathi)',short:'Monthly stipend and skill training support for unemployed youth in West Bengal.',category:'Employment',state:'West Bengal',authority:'Department of Youth Services, WB',benefit:'Monthly stipend and vocational training',age:{min:18,max:45},incomeMax:250000,occupations:['Unemployed','Student'],categories:['SC','ST','OBC','General'],gender:['Any'],disability:'Any',documents:['Aadhaar','Educational Certificate','Bank Account Proof'],applicationUrl:'https://employmentbankwb.gov.in/'},
{id:'sch-wb03',name:'Sasthya Sathi',short:'Cashless health insurance coverage for all families of West Bengal.',category:'Health',state:'West Bengal',authority:'Department of Health & Family Welfare, WB',benefit:'Health insurance cover up to Rs. 5 lakh per family per year',age:{min:0,max:120},incomeMax:1000000,occupations:['Any'],categories:['SC','ST','OBC','General'],gender:['Any'],disability:'Any',documents:['Aadhaar','Residence Certificate'],applicationUrl:'https://swasthyasathi.gov.in/'},
{id:'sch-wb04',name:'Kanyashree Prakalpa',short:'Conditional cash transfer to improve status and wellbeing of adolescent girls.',category:'Education',state:'West Bengal',authority:'Department of Women & Child Development, WB',benefit:'Annual scholarship and one-time grant on turning 18',age:{min:13,max:19},incomeMax:120000,occupations:['Student'],categories:['SC','ST','OBC','General'],gender:['Female'],disability:'Any',documents:['Aadhaar','Birth Certificate','Student ID'],applicationUrl:'https://wbkanyashree.gov.in/'},
{id:'sch-wb05',name:'Rupashree Prakalpa',short:'One-time financial grant for marriage of daughters from economically weaker families.',category:'Social Security',state:'West Bengal',authority:'Department of Women & Child Development, WB',benefit:'One-time grant of Rs. 25,000',age:{min:18,max:60},incomeMax:150000,occupations:['Any'],categories:['SC','ST','OBC','General'],gender:['Female'],disability:'Any',documents:['Aadhaar','Age Proof','Income Certificate','Bank Account Proof'],applicationUrl:'https://wbrupashree.gov.in/'},
{id:'sch-wb06',name:'Khadya Sathi',short:'Subsidised food grains distribution scheme ensuring food security for all residents.',category:'Food Security',state:'West Bengal',authority:'Department of Food & Supplies, WB',benefit:'Subsidised rice and wheat through ration shops',age:{min:0,max:120},incomeMax:1000000,occupations:['Any'],categories:['SC','ST','OBC','General'],gender:['Any'],disability:'Any',documents:['Aadhaar','Ration Card','Residence Certificate'],applicationUrl:'https://food.wb.gov.in/'},
{id:'sch-wb07',name:'Lakshmir Bhandar',short:'Monthly financial assistance to women heads of households to ensure financial independence.',category:'Social Security',state:'West Bengal',authority:'Department of Women & Child Development, WB',benefit:'Monthly assistance of Rs. 1,000-1,200',age:{min:25,max:60},incomeMax:200000,occupations:['Any'],categories:['SC','ST','OBC','General'],gender:['Female'],disability:'Any',documents:['Aadhaar','Bank Account Proof','Residence Certificate'],applicationUrl:'https://socialsecurity.wb.gov.in/'},
{id:'sch-wb08',name:'Krishak Bandhu',short:'Financial assistance and life insurance cover for farmers of West Bengal.',category:'Agriculture',state:'West Bengal',authority:'Department of Agriculture, WB',benefit:'Annual assistance per acre and Rs. 2 lakh life insurance',age:{min:18,max:70},incomeMax:300000,occupations:['Self-employed','Other'],categories:['SC','ST','OBC','General'],gender:['Any'],disability:'Any',documents:['Aadhaar','Land Records','Bank Account Proof'],applicationUrl:'https://krishakbandhu.wb.gov.in/'},
{id:'sch-wb09',name:'Manabik (Manabik Prakalpa)',short:'Monthly pension assistance for persons with disabilities in West Bengal.',category:'Disability',state:'West Bengal',authority:'Department of Women & Child Development, WB',benefit:'Monthly pension for persons with disabilities',age:{min:18,max:120},incomeMax:200000,occupations:['Any'],categories:['SC','ST','OBC','General'],gender:['Any'],disability:'Yes',documents:['Aadhaar','Disability Certificate','Bank Account Proof'],applicationUrl:'https://wbcaremanabik.gov.in/'},
{id:'sch-001',name:'National Means-cum-Merit Scholarship Scheme (NMMSS)',short:'Education assistance for eligible students from lower-income households.',category:'Education',state:'All India',authority:'Ministry of Education, Govt of India',benefit:'Annual education assistance',age:{min:16,max:30},incomeMax:300000,occupations:['Student'],categories:['SC','ST','OBC','General'],gender:['Any'],disability:'Any',documents:['Aadhaar','Income Certificate','Residence Certificate','Student ID'],applicationUrl:'https://scholarships.gov.in/'},
{id:'sch-002',name:'Prime Minister\'s Employment Generation Programme (PMEGP)',short:'Starter support for women planning a small income-generating enterprise.',category:'Livelihood',state:'All India',authority:'Ministry of MSME, Govt of India',benefit:'Enterprise support and training',age:{min:18,max:55},incomeMax:500000,occupations:['Self-employed','Unemployed','Worker'],categories:['SC','ST','OBC','General'],gender:['Female'],disability:'Any',documents:['Aadhaar','Income Certificate','Bank Account Proof','Residence Certificate'],applicationUrl:'https://www.kviconline.gov.in/pmegpeportal/pmegphome/index.jsp'},
{id:'sch-003',name:'Assistance to Disabled Persons for Purchase/Fitting of Aids and Appliances (ADIP)',short:'Support pathway for eligible citizens with disabilities.',category:'Disability',state:'All India',authority:'Ministry of Social Justice & Empowerment, Govt of India',benefit:'Assistive and social support',age:{min:18,max:100},incomeMax:600000,occupations:['Any'],categories:['SC','ST','OBC','General'],gender:['Any'],disability:'Yes',documents:['Aadhaar','Disability Certificate','Income Certificate','Bank Account Proof'],applicationUrl:'https://adip.depwd.gov.in/'},
{id:'sch-004',name:'Rashtriya Vayoshri Yojana (RVY)',short:'A guided route to social support for older residents.',category:'Social Security',state:'All India',authority:'Ministry of Social Justice & Empowerment, Govt of India',benefit:'Social-security assistance',age:{min:60,max:120},incomeMax:400000,occupations:['Any'],categories:['SC','ST','OBC','General'],gender:['Any'],disability:'Any',documents:['Aadhaar','Age Proof','Income Certificate','Bank Account Proof'],applicationUrl:'https://adip.depwd.gov.in/rvy'},
{id:'sch-005',name:'Pradhan Mantri Shram Yogi Maan-dhan Yojana (PM-SYM)',short:'Support pathway for eligible workers with lower household income.',category:'Livelihood',state:'All India',authority:'Ministry of Labour & Employment, Govt of India',benefit:'Worker welfare assistance',age:{min:18,max:60},incomeMax:350000,occupations:['Any'],categories:['SC','ST','OBC','General'],gender:['Any'],disability:'Any',documents:['Aadhaar','Income Certificate','Occupation Proof','Bank Account Proof'],applicationUrl:'https://maandhan.in/'},
{id:'sch-006',name:'Pradhan Mantri Awas Yojana (PMAY)',short:'A guided eligibility and document pathway for housing support.',category:'Housing',state:'All India',authority:'Ministry of Housing & Urban Affairs, Govt of India',benefit:'Housing assistance pathway',age:{min:18,max:80},incomeMax:450000,occupations:['Student','Worker','Self-employed','Unemployed','Retired','Other'],categories:['SC','ST','OBC','General'],gender:['Any'],disability:'Any',documents:['Aadhaar','Income Certificate','Residence Certificate','Bank Account Proof'],applicationUrl:'https://pmaymis.gov.in/'} 
,{id:'sch-wb10',name:'Taposili Bandhu',short:'Old age pension for SC citizens of West Bengal.',category:'Social Security',state:'West Bengal',authority:'Department of Backward Classes Welfare, WB',benefit:'Monthly pension of Rs. 1000',age:{min:60,max:120},incomeMax:200000,occupations:['Any'],categories:['SC'],gender:['Any'],disability:'Any',documents:['Aadhaar','Age Proof','Caste Certificate','Bank Account Proof'],applicationUrl:'https://jaibangla.wb.gov.in/'}
,{id:'sch-wb11',name:'Jai Johar',short:'Old age pension for ST citizens of West Bengal.',category:'Social Security',state:'West Bengal',authority:'Department of Backward Classes Welfare, WB',benefit:'Monthly pension of Rs. 1000',age:{min:60,max:120},incomeMax:200000,occupations:['Any'],categories:['ST'],gender:['Any'],disability:'Any',documents:['Aadhaar','Age Proof','Caste Certificate','Bank Account Proof'],applicationUrl:'https://adibasikalyan.gov.in/'}
,{id:'sch-wb12',name:'IGNOAPS (National Old Age Pension)',short:'National pension scheme for BPL elderly citizens.',category:'Social Security',state:'All India',authority:'Ministry of Rural Development, Govt of India',benefit:'Monthly pension for elderly',age:{min:60,max:120},incomeMax:100000,occupations:['Any'],categories:['Any'],gender:['Any'],disability:'Any',documents:['Aadhaar','Age Proof','BPL Certificate','Bank Account Proof'],applicationUrl:'https://nsap.nic.in/'}
,{id:'sch-wb13',name:'IGNWPS (National Widow Pension)',short:'National pension scheme for BPL widows.',category:'Social Security',state:'All India',authority:'Ministry of Rural Development, Govt of India',benefit:'Monthly pension for widows',age:{min:40,max:120},incomeMax:100000,occupations:['Any'],categories:['Any'],gender:['Female'],disability:'Any',documents:['Aadhaar','Age Proof','BPL Certificate','Husband Death Certificate'],applicationUrl:'https://nsap.nic.in/'}
];
export const complaintsSeed=[
{id:'WB-KOL-4821',category:'Waste Management',location:'Ward 42',status:'Under Review',priority:'High',created:'2h ago',department:'Municipal Services'},
{id:'WB-KOL-4818',category:'Road',location:'Ward 17',status:'Resolved',priority:'Medium',created:'Yesterday',department:'Roads'},
{id:'WB-KOL-4807',category:'Water',location:'Ward 09',status:'Assigned',priority:'High',created:'Yesterday',department:'Water Supply'},
{id:'WB-KOL-4794',category:'Safety',location:'Ward 31',status:'Escalated',priority:'Critical',created:'3 days ago',department:'Public Safety'},
{id:'WB-KOL-4779',category:'Sanitation',location:'Ward 22',status:'Resolved',priority:'Medium',created:'4 days ago',department:'Municipal Services'}];
export const profileDefaults={name:'',age:21,state:'West Bengal',district:'Kolkata',income:150000,occupation:'Student',category:'OBC',gender:'Male',disability:'No'};
