export const schemes=[
{id:'sch-001',name:'National Means-cum-Merit Scholarship Scheme (NMMSS)',short:'Education assistance for eligible students from lower-income households.',category:'Education',state:'West Bengal',authority:'State Education Department',benefit:'Annual education assistance',age:{min:16,max:30},incomeMax:300000,occupations:['Student'],categories:['SC','ST','OBC','General'],gender:['Any'],disability:'Any',documents:['Aadhaar','Income Certificate','Residence Certificate','Student ID'],applicationUrl:'https://scholarships.gov.in/'},
{id:'sch-002',name:'Prime Minister\'s Employment Generation Programme (PMEGP)',short:'Starter support for women planning a small income-generating enterprise.',category:'Livelihood',state:'West Bengal',authority:'State Livelihood Mission',benefit:'Enterprise support and training',age:{min:18,max:55},incomeMax:500000,occupations:['Self-employed','Unemployed','Worker'],categories:['SC','ST','OBC','General'],gender:['Female'],disability:'Any',documents:['Aadhaar','Income Certificate','Bank Account Proof','Residence Certificate'],applicationUrl:'https://www.kviconline.gov.in/pmegpeportal/pmegphome/index.jsp'},
{id:'sch-003',name:'Assistance to Disabled Persons for Purchase/Fitting of Aids and Appliances (ADIP)',short:'Support pathway for eligible citizens with disabilities.',category:'Disability',state:'West Bengal',authority:'Social Welfare Department',benefit:'Assistive and social support',age:{min:18,max:100},incomeMax:600000,occupations:['Student','Worker','Self-employed','Unemployed','Other'],categories:['SC','ST','OBC','General'],gender:['Any'],disability:'Yes',documents:['Aadhaar','Disability Certificate','Income Certificate','Bank Account Proof'],applicationUrl:'https://adip.depwd.gov.in/'},
{id:'sch-004',name:'Rashtriya Vayoshri Yojana (RVY)',short:'A guided route to social support for older residents.',category:'Social Security',state:'West Bengal',authority:'Social Welfare Department',benefit:'Social-security assistance',age:{min:60,max:120},incomeMax:400000,occupations:['Retired','Other'],categories:['SC','ST','OBC','General'],gender:['Any'],disability:'Any',documents:['Aadhaar','Age Proof','Income Certificate','Bank Account Proof'],applicationUrl:'https://adip.depwd.gov.in/rvy'},
{id:'sch-005',name:'Pradhan Mantri Shram Yogi Maan-dhan Yojana (PM-SYM)',short:'Support pathway for eligible workers with lower household income.',category:'Livelihood',state:'West Bengal',authority:'Labour Department',benefit:'Worker welfare assistance',age:{min:18,max:60},incomeMax:350000,occupations:['Worker','Self-employed'],categories:['SC','ST','OBC','General'],gender:['Any'],disability:'Any',documents:['Aadhaar','Income Certificate','Occupation Proof','Bank Account Proof'],applicationUrl:'https://maandhan.in/'},
{id:'sch-006',name:'Pradhan Mantri Awas Yojana (PMAY)',short:'A guided eligibility and document pathway for housing support.',category:'Housing',state:'West Bengal',authority:'Housing & Urban Development',benefit:'Housing assistance pathway',age:{min:18,max:80},incomeMax:450000,occupations:['Student','Worker','Self-employed','Unemployed','Retired','Other'],categories:['SC','ST','OBC','General'],gender:['Any'],disability:'Any',documents:['Aadhaar','Income Certificate','Residence Certificate','Bank Account Proof'],applicationUrl:'https://pmaymis.gov.in/'}];,
{id:'sch-007',name:'Lakshmir Bhandar',short:'Monthly financial assistance to eligible women heads of household in West Bengal.',category:'Women Welfare',state:'West Bengal',authority:'Women & Child Development Dept',benefit:'Monthly cash assistance',age:{min:25,max:60},incomeMax:500000,occupations:['Unemployed','Self-employed','Worker','Other'],categories:['SC','ST','OBC','General'],gender:['Female'],disability:'Any',documents:['Aadhaar','Bank Account Proof','Residence Certificate'],applicationUrl:'https://socialsecurity.wb.gov.in/'},
{id:'sch-008',name:'Kanyashree Prakalpa',short:'Conditional cash transfer to improve status and wellbeing of girl children in West Bengal.',category:'Education',state:'West Bengal',authority:'Women & Child Development Dept',benefit:'Annual/One-time scholarship',age:{min:13,max:19},incomeMax:120000,occupations:['Student'],categories:['SC','ST','OBC','General'],gender:['Female'],disability:'Any',documents:['Aadhaar','Bank Account Proof','Student ID'],applicationUrl:'https://wbkanyashree.gov.in/'},
{id:'sch-009',name:'Rupashree Prakalpa',short:'One-time financial assistance for marriage of economically disadvantaged women in West Bengal.',category:'Women Welfare',state:'West Bengal',authority:'Women & Child Development Dept',benefit:'One-time cash grant',age:{min:18,max:40},incomeMax:150000,occupations:['Unemployed','Other'],categories:['SC','ST','OBC','General'],gender:['Female'],disability:'Any',documents:['Aadhaar','Income Certificate','Bank Account Proof'],applicationUrl:'https://wbrupashree.gov.in/'},
{id:'sch-010',name:'Khadya Sathi',short:'Subsidized food grains distribution scheme for residents of West Bengal.',category:'Food Security',state:'West Bengal',authority:'Food & Supplies Department',benefit:'Subsidized ration',age:{min:18,max:100},incomeMax:600000,occupations:['Student','Worker','Self-employed','Unemployed','Retired','Other'],categories:['SC','ST','OBC','General'],gender:['Any'],disability:'Any',documents:['Aadhaar','Ration Card'],applicationUrl:'https://food.wb.gov.in/'},
{id:'sch-011',name:'Swasthya Sathi',short:'Health insurance coverage for families in West Bengal for cashless treatment.',category:'Healthcare',state:'West Bengal',authority:'Health & Family Welfare Dept',benefit:'Health insurance up to Rs. 5 lakh',age:{min:0,max:120},incomeMax:1000000,occupations:['Student','Worker','Self-employed','Unemployed','Retired','Other'],categories:['SC','ST','OBC','General'],gender:['Any'],disability:'Any',documents:['Aadhaar','Swasthya Sathi Card'],applicationUrl:'https://swasthyasathi.gov.in/'},
{id:'sch-012',name:'Krishak Bandhu',short:'Financial assistance and life insurance cover for farmers in West Bengal.',category:'Agriculture',state:'West Bengal',authority:'Agriculture Department',benefit:'Seasonal financial assistance and insurance',age:{min:18,max:100},incomeMax:800000,occupations:['Self-employed','Worker','Other'],categories:['SC','ST','OBC','General'],gender:['Any'],disability:'Any',documents:['Aadhaar','Land Records','Bank Account Proof'],applicationUrl:'https://krishakbandhu.net/'},
{id:'sch-013',name:'Manabik',short:'Monthly pension assistance for persons with disabilities in West Bengal.',category:'Disability',state:'West Bengal',authority:'Social Welfare Department',benefit:'Monthly pension',age:{min:18,max:100},incomeMax:400000,occupations:['Unemployed','Other','Student'],categories:['SC','ST','OBC','General'],gender:['Any'],disability:'Yes',documents:['Aadhaar','Disability Certificate','Bank Account Proof'],applicationUrl:'https://wbsje.gov.in/'},
{id:'sch-014',name:'Yuvashree/Yuva Sathi',short:'Unemployment allowance and skill support scheme for youth in West Bengal.',category:'Employment',state:'West Bengal',authority:'Labour Department',benefit:'Monthly unemployment allowance',age:{min:18,max:45},incomeMax:300000,occupations:['Unemployed'],categories:['SC','ST','OBC','General'],gender:['Any'],disability:'Any',documents:['Aadhaar','Education Certificate','Bank Account Proof'],applicationUrl:'https://employmentbankwb.gov.in/'},
{id:'sch-015',name:'Annapurna Bhandar Scheme',short:'Retail support scheme providing subsidized essentials through local shops in West Bengal.',category:'Food Security',state:'West Bengal',authority:'Food & Supplies Department',benefit:'Subsidized essential commodities',age:{min:18,max:100},incomeMax:500000,occupations:['Self-employed','Worker','Unemployed','Other'],categories:['SC','ST','OBC','General'],gender:['Any'],disability:'Any',documents:['Aadhaar','Ration Card'],applicationUrl:'https://food.wb.gov.in/'}
export const complaintsSeed=[
{id:'WB-KOL-4821',category:'Waste Management',location:'Ward 42',status:'Under Review',priority:'High',created:'2h ago',department:'Municipal Services'},
{id:'WB-KOL-4818',category:'Road',location:'Ward 17',status:'Resolved',priority:'Medium',created:'Yesterday',department:'Roads'},
{id:'WB-KOL-4807',category:'Water',location:'Ward 09',status:'Assigned',priority:'High',created:'Yesterday',department:'Water Supply'},
{id:'WB-KOL-4794',category:'Safety',location:'Ward 31',status:'Escalated',priority:'Critical',created:'3 days ago',department:'Public Safety'},
{id:'WB-KOL-4779',category:'Sanitation',location:'Ward 22',status:'Resolved',priority:'Medium',created:'4 days ago',department:'Municipal Services'}];
export const profileDefaults={name:'',age:21,state:'West Bengal',district:'Kolkata',income:150000,occupation:'Student',category:'OBC',gender:'Male',disability:'No'};
