export const schemes=[
{id:'sch-001',name:'Student Education Support',short:'Education assistance for eligible students from lower-income households.',category:'Education',state:'West Bengal',authority:'State Education Department',benefit:'Annual education assistance',age:{min:16,max:30},incomeMax:300000,occupations:['Student'],categories:['SC','ST','OBC','General'],gender:['Any'],disability:'Any',documents:['Aadhaar','Income Certificate','Residence Certificate','Student ID'],applicationUrl:'https://www.wb.gov.in/'},
{id:'sch-002',name:'Women Enterprise Starter',short:'Starter support for women planning a small income-generating enterprise.',category:'Livelihood',state:'West Bengal',authority:'State Livelihood Mission',benefit:'Enterprise support and training',age:{min:18,max:55},incomeMax:500000,occupations:['Self-employed','Unemployed','Worker'],categories:['SC','ST','OBC','General'],gender:['Female'],disability:'Any',documents:['Aadhaar','Income Certificate','Bank Account Proof','Residence Certificate'],applicationUrl:'https://www.wb.gov.in/'},
{id:'sch-003',name:'Accessible Living Assistance',short:'Support pathway for eligible citizens with disabilities.',category:'Disability',state:'West Bengal',authority:'Social Welfare Department',benefit:'Assistive and social support',age:{min:18,max:100},incomeMax:600000,occupations:['Student','Worker','Self-employed','Unemployed','Other'],categories:['SC','ST','OBC','General'],gender:['Any'],disability:'Yes',documents:['Aadhaar','Disability Certificate','Income Certificate','Bank Account Proof'],applicationUrl:'https://www.wb.gov.in/'},
{id:'sch-004',name:'Senior Citizen Support Pathway',short:'A guided route to social support for older residents.',category:'Social Security',state:'West Bengal',authority:'Social Welfare Department',benefit:'Social-security assistance',age:{min:60,max:120},incomeMax:400000,occupations:['Retired','Other'],categories:['SC','ST','OBC','General'],gender:['Any'],disability:'Any',documents:['Aadhaar','Age Proof','Income Certificate','Bank Account Proof'],applicationUrl:'https://www.wb.gov.in/'},
{id:'sch-005',name:'Worker Welfare Assistance',short:'Support pathway for eligible workers with lower household income.',category:'Livelihood',state:'West Bengal',authority:'Labour Department',benefit:'Worker welfare assistance',age:{min:18,max:60},incomeMax:350000,occupations:['Worker','Self-employed'],categories:['SC','ST','OBC','General'],gender:['Any'],disability:'Any',documents:['Aadhaar','Income Certificate','Occupation Proof','Bank Account Proof'],applicationUrl:'https://www.wb.gov.in/'},
{id:'sch-006',name:'General Housing Assistance',short:'A guided eligibility and document pathway for housing support.',category:'Housing',state:'West Bengal',authority:'Housing & Urban Development',benefit:'Housing assistance pathway',age:{min:18,max:80},incomeMax:450000,occupations:['Student','Worker','Self-employed','Unemployed','Retired','Other'],categories:['SC','ST','OBC','General'],gender:['Any'],disability:'Any',documents:['Aadhaar','Income Certificate','Residence Certificate','Bank Account Proof'],applicationUrl:'https://www.wb.gov.in/'}];
export const complaintsSeed=[
{id:'WB-KOL-4821',category:'Waste Management',location:'Ward 42',status:'Under Review',priority:'High',created:'2h ago',department:'Municipal Services'},
{id:'WB-KOL-4818',category:'Road',location:'Ward 17',status:'Resolved',priority:'Medium',created:'Yesterday',department:'Roads'},
{id:'WB-KOL-4807',category:'Water',location:'Ward 09',status:'Assigned',priority:'High',created:'Yesterday',department:'Water Supply'},
{id:'WB-KOL-4794',category:'Safety',location:'Ward 31',status:'Escalated',priority:'Critical',created:'3 days ago',department:'Public Safety'},
{id:'WB-KOL-4779',category:'Sanitation',location:'Ward 22',status:'Resolved',priority:'Medium',created:'4 days ago',department:'Municipal Services'}];
export const profileDefaults={name:'',age:21,state:'West Bengal',district:'Kolkata',income:150000,occupation:'Student',category:'OBC',gender:'Male',disability:'No'};
